In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
df = pd.read_csv(r"C:\Users\HP\Desktop\data science\datascience\data.csv")
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [100]:
df.head()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [101]:
df.tail()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [ ]:
pl

In [103]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='str')

In [104]:
df['brand']

0          HP
1          HP
2        Acer
3      Lenovo
4       Apple
        ...
888      Asus
889      Asus
890      Asus
891      Asus
892      Asus
Name: brand, Length: 893, dtype: str

In [158]:
df[df['brand']=="Apple"]

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,1
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,1
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,DDR4,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,1
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,Unified,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,1
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,DDR4,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
215,224,253,Apple,MacBook Pro 16 Laptop,201498,81.000000,9th Gen Intel Core i9,Octa Core,32GB,DDR4,2TB,SSD,4GB Radeon Pro 5500M,16.0,3072.0,1920.0,Mac Catalina OS,1
375,395,436,Apple,MacBook Pro 14 inch Laptop,290990,61.000000,Apple M2 Max M2 Max,12 Cores,32GB,Unified,1TB,SSD,30-core GPU,14.2,3024.0,1964.0,Mac OS,1
376,396,437,Apple,MacBook Pro 14 inch Laptop,234990,69.323529,Apple M2 Pro M2 Pro,12 Cores,16GB,Unified,1TB,SSD,19-core GPU,14.2,3024.0,1964.0,Mac OS,1
468,489,555,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,239900,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,Unified,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,1
469,490,556,Apple,MacBook Pro 16 inch MK1A3HN Laptop,309490,60.000000,Apple M1 Max M1 Max,10 Cores,32GB,Unified,1TB,SSD,32-core GPU,16.2,3456.0,2234.0,Mac OS,1
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,DDR3,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,1
504,528,599,Apple,MacBook Pro 16 inch MK183HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores,16GB,Unified,512GB,SSD,16-core GPU,16.2,3456.0,2234.0,Mac OS,1
505,529,600,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,Unified,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,1
513,537,611,Apple,MacBook Air 2020 Laptop,72999,69.323529,10th Gen Intel Core i3,"Quad Core, 8 Threads",8GB,LPDDR4X,256GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,0
514,538,612,Apple,MacBook Air 2020 Laptop,109999,69.323529,10th Gen Intel Core i7,"Quad Core, 8 Threads",8GB,LPDDR4X,512GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,0

In [105]:
df[["brand"]]

      brand
0        HP
1        HP
2      Acer
3    Lenovo
4     Apple
..      ...
888    Asus
889    Asus
890    Asus
891    Asus
892    Asus

[893 rows x 1 columns]

In [106]:
df[['brand','name']]

      brand                                               name
0        HP                   Victus 15-fb0157AX Gaming Laptop
1        HP                                15s-fq5007TU Laptop
2      Acer                               One 14 Z8-415 Laptop
3    Lenovo               Yoga Slim 6 14IAP8 82WU0095IN Laptop
4     Apple                    MacBook Air 2020 MGND3HN Laptop
..      ...                                                ...
888    Asus          Vivobook 15X 2023 K3504VAB-NJ321WS Laptop
889    Asus                     TUF A15 FA577RM-HQ032WS Laptop
890    Asus  ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...
891    Asus  TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop
892    Asus  TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop

[893 rows x 2 columns]

In [107]:
df["brand"].unique()

<StringArray>
[       'HP',      'Acer',    'Lenovo',     'Apple',      'Dell',      'Asus',
   'Samsung',   'Ultimus', 'Primebook',       'MSI',   'Infinix',     'Wings',
     'Honor', 'Zebronics',    'Xiaomi',     'iBall',     'Chuwi',    'Realme',
     'Avita',    'Walker',    'Huawei',     'Tecno',  'Gigabyte',      'Vaio',
 'Microsoft',   'Fujitsu',        'LG',   'Ninkear',     'Razer',       'AXL']
Length: 30, dtype: str

In [108]:
df["brand"].nunique()

30

In [109]:
df["brand"].value_counts()

brand
HP           186
Lenovo       169
Asus         157
Dell         107
Acer          84
MSI           65
Samsung       28
Apple         16
Infinix       15
LG             9
Xiaomi         8
Gigabyte       8
Fujitsu        6
Ultimus        4
Zebronics      4
Wings          3
Chuwi          3
Realme         3
Tecno          3
Honor          2
Huawei         2
Microsoft      2
AXL            2
Primebook      1
iBall          1
Avita          1
Walker         1
Vaio           1
Ninkear        1
Razer          1
Name: count, dtype: int64

In [110]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
888    False
889    False
890    False
891    False
892    False
Length: 893, dtype: bool

In [111]:
df.duplicated().sum()

np.int64(0)

In [112]:
df.drop_duplicates() # this have no duplicate values 
# so it will the same as it is and don't drop any duplicate 
# values

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [113]:
df.drop_duplicates(inplace=True) # this will delete the duplicate
# values permanently

In [114]:
df.isnull() # it will show if there is any null value
# or not

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
891,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
892,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [115]:
df.isnull().sum() # the sum of null will be zero because
# no null values

Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [116]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [117]:
# there is 4 float columns and 4 int columns and 10 
# string values we can convert it

In [118]:
df['OS'].unique()

<StringArray>
[     'Windows 11 OS',             'Mac OS',      'Android 11 OS',
             'DOS OS',      'Windows 10 OS',     'Windows 10  OS',
          'Chrome OS',         'Windows OS',          'Ubuntu OS',
    'Mac Catalina OS',         'DOS 3.0 OS',     'Windows 11  OS',
 'Mac High Sierra OS',   'Mac 10.15.3\t OS']
Length: 14, dtype: str

In [119]:
# we can any column form int to string , float to string
# str to int, or change into any other by creating dict and
# changing it by turning in.

In [120]:
df['warranty'].unique()

array([1, 0, 2, 3])

In [121]:
# warranty_dict = { 
#     1:"first",2:"second",3:"third",4:"forth"
# }

In [122]:
# df['warranty']=df['warranty'].map(warranty_dict)
# df

In [123]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [124]:
# df.drop('price',axis=1,inplace=True)
# df # in this we cut the column of price

In [125]:
# df.drop('ROM',axis=1,inplace=True)
# df

In [126]:
# df.drop(['brand','name'],axis=1,inplace=True)
# df # we use list to remove two columns at one time
# # in the

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [128]:
obj_val = df.select_dtypes(include='O')

C:\Users\HP\AppData\Local\Temp\ipykernel_4844\122132474.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val = df.select_dtypes(include='O')

In [129]:
obj_val

,brand,name,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,OS
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,Windows 11 OS
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,Mac OS
...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS

In [130]:
num_val=df.select_dtypes(exclude='O')
num_val

,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height,warranty
0,0,0,49900,73.000000,15.6,1920.0,1080.0,1
1,1,1,39900,60.000000,15.6,1920.0,1080.0,1
2,2,2,26990,69.323529,14.0,1920.0,1080.0,1
3,3,3,59729,66.000000,14.0,2240.0,1400.0,1
4,4,4,69990,69.323529,13.3,2560.0,1600.0,1
...,...,...,...,...,...,...,...,...
888,926,1015,44990,69.323529,15.6,1920.0,1080.0,1
889,927,1016,110000,71.000000,15.6,2560.0,1440.0,1
890,928,1017,189990,89.000000,14.0,2560.0,1600.0,1
891,929,1018,129990,73.000000,15.6,1920.0,1080.0,1
892,930,1019,131990,84.000000,15.6,1920.0,1080.0,1

In [131]:
num_val.columns # it contains all the string values

Index(['Unnamed: 0.1', 'Unnamed: 0', 'price', 'spec_rating', 'display_size',
       'resolution_width', 'resolution_height', 'warranty'],
      dtype='str')

In [132]:
obj_val.columns # it contains value of int and float

Index(['brand', 'name', 'processor', 'CPU', 'Ram', 'Ram_type', 'ROM',
       'ROM_type', 'GPU', 'OS'],
      dtype='str')

In [133]:
complete_Data =pd.concat([obj_val,num_val],axis=1)
complete_Data

,brand,name,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,OS,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height,warranty
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS,0,0,49900,73.000000,15.6,1920.0,1080.0,1
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,Windows 11 OS,1,1,39900,60.000000,15.6,1920.0,1080.0,1
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS,2,2,26990,69.323529,14.0,1920.0,1080.0,1
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS,3,3,59729,66.000000,14.0,2240.0,1400.0,1
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,Mac OS,4,4,69990,69.323529,13.3,2560.0,1600.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS,926,1015,44990,69.323529,15.6,1920.0,1080.0,1
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS,927,1016,110000,71.000000,15.6,2560.0,1440.0,1
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS,928,1017,189990,89.000000,14.0,2560.0,1600.0,1
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,929,1018,129990,73.000000,15.6,1920.0,1080.0,1
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,930,1019,131990,84.000000,15.6,1920.0,1080.0,1

In [136]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [135]:
# now we will do filtering take out a single type of laptop
hp_brand = df[df['brand']=='HP']
hp_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
18,19,19,HP,Victus 15-fa0666TX Gaming Laptop,68990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
23,24,24,HP,15s-fq2510tu Laptop,49580,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",16GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
25,26,26,HP,15s-eq2132AU Laptop,43990,63.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",16GB,DDR4,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,903,992,HP,Victus 15-fb0137AX Gaming Laptop,74990,67.000000,5th Gen AMD Ryzen 7 5800H,"Octa Core, 16 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
867,905,994,HP,ProBook 445 G8 7K2J8PA Business Laptop,46490,63.000000,5th Gen AMD Ryzen 7 5800U,"Octa Core, 16 Threads",8GB,DDR4,512GB,SSD,AMD Radeon,14.0,1920.0,1080.0,DOS OS,1
872,910,999,HP,Victus 15-fb0131AX Gaming Laptop,51990,65.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 5600M,15.6,1920.0,1080.0,Windows 11 OS,1
876,914,1003,HP,15s-fq3071TU Laptop,28490,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD Graphics,15.0,1366.0,768.0,Windows 11 OS,1
880,918,1007,HP,Victus 15-fb0135AX Gaming Laptop,59990,64.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1

In [137]:
hp_price=hp_brand[hp_brand['price']<=100000]
hp_price

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
18,19,19,HP,Victus 15-fa0666TX Gaming Laptop,68990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
23,24,24,HP,15s-fq2510tu Laptop,49580,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",16GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
25,26,26,HP,15s-eq2132AU Laptop,43990,63.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",16GB,DDR4,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,903,992,HP,Victus 15-fb0137AX Gaming Laptop,74990,67.000000,5th Gen AMD Ryzen 7 5800H,"Octa Core, 16 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
867,905,994,HP,ProBook 445 G8 7K2J8PA Business Laptop,46490,63.000000,5th Gen AMD Ryzen 7 5800U,"Octa Core, 16 Threads",8GB,DDR4,512GB,SSD,AMD Radeon,14.0,1920.0,1080.0,DOS OS,1
872,910,999,HP,Victus 15-fb0131AX Gaming Laptop,51990,65.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 5600M,15.6,1920.0,1080.0,Windows 11 OS,1
876,914,1003,HP,15s-fq3071TU Laptop,28490,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD Graphics,15.0,1366.0,768.0,Windows 11 OS,1
880,918,1007,HP,Victus 15-fb0135AX Gaming Laptop,59990,64.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1

In [139]:
hp_warranty=hp_price[hp_price['warranty']==3]
hp_warranty

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
481,503,570,HP,EliteBook 840 G6,90464,69.323529,8th Gen Intel Core i5 8265U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Integrated UHD Graphics 620,14.0,1920.0,1080.0,Windows 10 OS,3

In [ ]:
# This we take out we found the hp laptop which
# is less than 100000 price and have 3 year warranty

In [140]:
Acer_brand=df[df['brand']=='Acer']
Acer_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
7,7,7,Acer,Nitro V ANV15-51 2023 Gaming Laptop,76990,63.000000,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
22,23,23,Acer,Aspire 7 A715-76G UN.QMYSI.002 Gaming Laptop,54990,72.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,1
27,28,29,Acer,Extensa 15 EX215-33 2023 Laptop,28990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,1
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
881,919,1008,Acer,Swift Edge 16 2023 Laptop,107399,69.323529,7th Gen AMD Ryzen 7040 Series 040,"Octa Core, 16 Threads",16GB,LPDDR5,1TB,SSD,AMD Radeon AMD,16.0,3840.0,2400.0,Windows 11 OS,1
886,924,1013,Acer,Aspire Vero AV14-52P NX.KJTSI.002 Laptop,49990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",16GB,LPDDR4X,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,1
887,925,1014,Acer,Aspire 5 A515-58M NX.KHGSI.002 Gaming Laptop,56990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,1

In [141]:
acer_ram=Acer_brand[Acer_brand['Ram']=="8GB"]
acer_ram

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
27,28,29,Acer,Extensa 15 EX215-33 2023 Laptop,28990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
82,84,87,Acer,Aspire Lite AL15-51 UN.431SI.288 Laptop,38990,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris XE Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
130,134,148,Acer,Aspire 5 A515-58P NX.KHJSI.001 Gaming Laptop,39965,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,LPDDR5,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
137,141,155,Acer,Aspire 3 A315-24P NX.KDESI.003 Laptop,27990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon Graphiics,15.6,1920.0,1080.0,Windows 11 OS,1
151,157,177,Acer,Aspire Lite 2023 AL15-51 Laptop,39990,62.000000,11th Gen Intel Core i5 1155G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
186,192,215,Acer,Extensa 15 EX215-33 Laptop,29990,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,LPDDR5,256GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
198,204,232,Acer,One 14 Z2-493 Laptop,25449,69.323529,3rd Gen AMD Ryzen 3 3250U,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
199,205,233,Acer,Aspire 3 A315-59 Laptop,33207,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
239,252,284,Acer,One 11 Z8-284 UN.013SI.033 Laptop,17990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,128GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
256,272,305,Acer,Aspire 5 A515-58M NX.KHFSI.003 Gaming Laptop,41990,69.323529,13th Gen Intel Core i3 1305U,"5 Cores (1P + 4E), 6 Threads",8GB,DDR5,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
284,301,337,Acer,Nitro 5 AN515-58 NH.QFHSI.008 Gaming Laptop,65999,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
285,302,338,Acer,Aspire Lite AL15-51 2023 Laptop,35990,69.323529,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
292,311,349,Acer,Swift 3 OLED SF314-71 NX.K9PSI.003 Laptop,54990,63.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",8GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2880.0,1800.0,Windows 11 OS,1
304,323,362,Acer,Aspire 3 NX.KDESI.008 Laptop,30990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,DDR5,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,1
316,335,375,Acer,One 14 Z8-415UN.599SI.009 Laptop,25990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
353,372,413,Acer,Nitro 5 AN515-47 NH.QL3SI.001 Gaming Laptop,78400,71.000000,7th Gen AMD Ryzen 5 7535HS,"Hexa Core, 12 Threads",8GB,DDR5,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
396,416,468,Acer,Nitro 5 AN515-47 NH.QL3SI.001 Gaming Laptop,64990,71.000000,7th Gen AMD Ryzen 5 7535HS,"Hexa Core, 12 Threads",8GB,DDR5,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
404,424,479,Acer,Aspire 3 A315-24P NX.KDESI.004 Laptop,37990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon Graphiics,15.6,1920.0,1080.0,Windows 11 OS,1
418,438,501,Acer,Aspire 5 A515-57 NX.K2VSI.002 Laptop,36990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
434,454,518,Acer,Extensa 15 EX215-54 Laptop,31500,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
451,472,536,Acer,Aspire 5 A515-57G Gaming Laptop,52128,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,1
452,473,537,Acer,Aspire 3 A315-59 Laptop,39990,69.323529,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
464,485,549,Acer,Aspire 3 A315-58 Laptop UN.ADDSI.036 Laptop,31500,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows OS,1
482,504,571,Acer,Swift SF514-52T NX.GTMSI.025 Laptop,54490,61.000000,8th Gen Intel Core i5 8250U,"Quad Core, 8 Threads",8GB,DDR3,512GB,SSD,Intel Integrated UHD 620,14.0,1920.0,1080.0,Windows 10 OS,1
491,515,583,Acer,Swift 3 SF314-512 NX.K0FSI.002 Laptop,59990,69.323529,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,LPDDR4X,512GB,SSD,Intel Integrated Iris Xe,14.0,2560.0,1440.0,Windows 11 OS,1
524,548,626,Acer,Aspire 3 A315-24P NX.KDESI.00B Laptop,33990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,1
539,563,643,Acer,Chromebook CB314-3H NX.K04SI.008 Laptop,26920,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,LPDDR4X,64GB,SSD,Intel Integrated UHD,14.0,1080.0,1920.0,Chrome OS,1
546,570,650,Acer,One 11 Z8-284 UN.013SI.032 Laptop,18990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
555,579,659,Acer,Aspire 5 A515-57G-58R7 Gaming Laptop,57999,67.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,1
573,598,678,Acer,Chromebook CB314-3H NX.K04SI.007 Laptop,26732,69.323529,Intel Celeron Dual Core N4500,"Dual Core, 2 Threads",8GB,LPDDR4X,128GB,SSD,Intel Integrated UHD,14.0,1280.0,1024.0,Chrome OS,1
652,684,766,Acer,TMP214-41-G3 UN.VSQSI.006 Notebook,36990,60.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Radeon AMD,14.0,1366.0,768.0,Windows 11 OS,1
664,696,778,Acer,Aspire 3 Spin 14 NX.KENSI.002 Laptop,39900,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,14.0,1920.0,1200.0,Windows 11 OS,1
700,734,818,Acer,Aspire 5 A515-56G NX.AT2SI.001 Laptop,44990,65.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,2GB NVIDIA GeForce MX450,15.6,1920.0,1080.0,Windows 11 OS,1
726,762,847,Acer,Nitro 16 ‎AN16-41 2023 Gaming Laptop,114990,78.000000,7th Gen AMD Ryzen 7 7840HS,"Octa Core, 16 Threads",8GB,DDR5,512GB,SSD,8GB NVIDIA GeForce RTX 4060,16.0,1920.0,1200.0,Windows 11 OS,1
727,763,848,Acer,Aspire 5 2023 A515-58M Gaming Laptop,80000,69.323529,13th Gen Intel Core i7 1355U,"10 Cores (2P + 8E), 12 Threads",8GB,LPDDR5,512GB,SSD,4GB NVIDIA GeForce RTX2050,15.6,1920.0,1080.0,Windows 11 OS,1
780,818,903,Acer,One 14 Z2-493 Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
801,839,924,Acer,Aspire 3 A315-510P Laptop,29980,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,DDR4,256GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
807,845,932,Acer,Aspire 5 A514-56M 2023 Gaming Laptop,51990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",8GB,LPDDR5,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1200.0,Windows 11 OS,1
810,848,935,Acer,One 14 2023 Z8-415 ‎Laptop,39990,69.323529,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
861,899,987,Acer,Aspire 3 A315-59 NX.K6TSI.00C Laptop,34990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,1
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1

In [142]:
acer_ram1=acer_ram[acer_ram['Ram_type']=="DDR4"]
acer_ram1

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
82,84,87,Acer,Aspire Lite AL15-51 UN.431SI.288 Laptop,38990,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris XE Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
151,157,177,Acer,Aspire Lite 2023 AL15-51 Laptop,39990,62.000000,11th Gen Intel Core i5 1155G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
198,204,232,Acer,One 14 Z2-493 Laptop,25449,69.323529,3rd Gen AMD Ryzen 3 3250U,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
199,205,233,Acer,Aspire 3 A315-59 Laptop,33207,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
239,252,284,Acer,One 11 Z8-284 UN.013SI.033 Laptop,17990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,128GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
284,301,337,Acer,Nitro 5 AN515-58 NH.QFHSI.008 Gaming Laptop,65999,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
285,302,338,Acer,Aspire Lite AL15-51 2023 Laptop,35990,69.323529,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
316,335,375,Acer,One 14 Z8-415UN.599SI.009 Laptop,25990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
418,438,501,Acer,Aspire 5 A515-57 NX.K2VSI.002 Laptop,36990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
434,454,518,Acer,Extensa 15 EX215-54 Laptop,31500,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
451,472,536,Acer,Aspire 5 A515-57G Gaming Laptop,52128,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,1
452,473,537,Acer,Aspire 3 A315-59 Laptop,39990,69.323529,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
464,485,549,Acer,Aspire 3 A315-58 Laptop UN.ADDSI.036 Laptop,31500,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows OS,1
546,570,650,Acer,One 11 Z8-284 UN.013SI.032 Laptop,18990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
555,579,659,Acer,Aspire 5 A515-57G-58R7 Gaming Laptop,57999,67.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 2050,15.6,1920.0,1080.0,Windows 11 OS,1
652,684,766,Acer,TMP214-41-G3 UN.VSQSI.006 Notebook,36990,60.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,AMD Radeon AMD,14.0,1366.0,768.0,Windows 11 OS,1
664,696,778,Acer,Aspire 3 Spin 14 NX.KENSI.002 Laptop,39900,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,14.0,1920.0,1200.0,Windows 11 OS,1
700,734,818,Acer,Aspire 5 A515-56G NX.AT2SI.001 Laptop,44990,65.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,2GB NVIDIA GeForce MX450,15.6,1920.0,1080.0,Windows 11 OS,1
780,818,903,Acer,One 14 Z2-493 Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
801,839,924,Acer,Aspire 3 A315-510P Laptop,29980,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,DDR4,256GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
810,848,935,Acer,One 14 2023 Z8-415 ‎Laptop,39990,69.323529,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
861,899,987,Acer,Aspire 3 A315-59 NX.K6TSI.00C Laptop,34990,69.323529,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
875,913,1002,Acer,Aspire 7 A715-76G NH.QMESI.003 Gaming Laptop,50990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce GTX 1650,15.6,1920.0,1080.0,Windows 11 OS,1
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1

In [143]:
acer_price=acer_ram1[acer_ram1['price']<=30000]
acer_price

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
198,204,232,Acer,One 14 Z2-493 Laptop,25449,69.323529,3rd Gen AMD Ryzen 3 3250U,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
239,252,284,Acer,One 11 Z8-284 UN.013SI.033 Laptop,17990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,128GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
316,335,375,Acer,One 14 Z8-415UN.599SI.009 Laptop,25990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,256GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
546,570,650,Acer,One 11 Z8-284 UN.013SI.032 Laptop,18990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1
780,818,903,Acer,One 14 Z2-493 Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,256GB,SSD,AMD Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
801,839,924,Acer,Aspire 3 A315-510P Laptop,29980,69.323529,Intel Core i3 N305,"Octa Core, 8 Threads",8GB,DDR4,256GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1

In [144]:
acer_space=acer_price[acer_price['ROM']=="128GB"]
acer_space

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
239,252,284,Acer,One 11 Z8-284 UN.013SI.033 Laptop,17990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,DDR4,128GB,SSD,Intel Integrated UHD,11.6,1366.0,768.0,Windows 11 OS,1

In [ ]:
# Above is the final laptop which suits all the conditions we gave.

In [156]:
df.query("brand=='Asus' and price<=30000 and Ram=='8GB' and ROM=='256GB'")
# if we want to do all in one than we can do it like this.

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
537,561,641,Asus,Vivobook Go 14 E410KA-EK013W Laptop,23990,69.323529,Intel N4500,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,1
866,904,993,Asus,Eeebook 15 E510MA-EJ011WS Laptop,25990,69.323529,Intel Celeron N4020,"Dual Core, 2 Threads",8GB,DDR4,256GB,SSD,Intel UHD Integrated,15.6,1920.0,1080.0,Windows 11 OS,1

In [154]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [159]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
888    False
889    False
890    False
891    False
892    False
Length: 893, dtype: bool

In [160]:
x=df.drop('price',axis=1)
x

,Unnamed: 0.1,Unnamed: 0,brand,name,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [161]:
y = df[['price']]
y

      price
0     49900
1     39900
2     26990
3     59729
4     69990
..      ...
888   44990
889  110000
890  189990
891  129990
892  131990

[893 rows x 1 columns]

In [1]:
# y = mx + c 
# this is called linear regression 
# this is what a straight line equation is
# thisss issss theeeee enddddddddddddd!