In [47]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [48]:
df = pd.read_csv(r"C:\Users\HP\Desktop\Data Science\SITP-12-Th-may-\Machine learning\Project\Furniture\clean_furniture_data.csv")
df

,Unnamed: 0,furniture,type,url,rate,delivery,sale,price
0,0,Bed side table with storage shelf,Home Decor Center,https://www.jumia.com.eg//ar/home-decor-center...,3.3,172.14,72%,2500.0
1,1,Bed side table with storage shelf,Modern Home,https://www.jumia.com.eg//ar/modern-home-bedsi...,0.0,172.14,54%,1200.0
2,2,Modern Zigzag TV Table,Modern Home,https://www.jumia.com.eg//ar/generic-zigzag-tv...,0.0,172.14,18%,1099.0
3,3,Bedside table with storage shelf,Modern Home,https://www.jumia.com.eg//ar/modern-home-bedsi...,0.0,172.14,58%,1200.0
4,4,Wall Mounted TV Unit with Cabinet TV Stand Uni...,Modern Home,https://www.jumia.com.eg//ar/modern-home-wall-...,5.0,52.44,54%,1400.0
...,...,...,...,...,...,...,...,...
1995,1995,Casio Standard Analogue Ladys Standard Analog ...,Casio Standard Analogue Ladys Standard Analog ...,https://www.jumia.com.eg//ar/casio-standard-an...,0.0,656.28,0%,1632.0
1996,1996,Coffee table + side table,Hub Furniture,https://www.jumia.com.eg//ar/hub-furniture-ae-...,0.0,172.14,0%,11450.0
1997,1997,Ben Togo Baby Bed,Bean GO,https://www.jumia.com.eg//ar/bean2go-newborn-b...,0.0,52.44,0%,550.0
1998,1998,Cloud memory foam mattress (medical),CIREM,https://www.jumia.com.eg//ar/cirem-cloud-memor...,0.0,172.14,9%,8495.0
1999,1999,Comfy memory foam mattress,CIREM,https://www.jumia.com.eg//ar/cirem-comfy-medic...,0.0,172.14,10%,10775.0

In [49]:
df.drop("url",axis=1,inplace=True)

In [50]:
df

,Unnamed: 0,furniture,type,rate,delivery,sale,price
0,0,Bed side table with storage shelf,Home Decor Center,3.3,172.14,72%,2500.0
1,1,Bed side table with storage shelf,Modern Home,0.0,172.14,54%,1200.0
2,2,Modern Zigzag TV Table,Modern Home,0.0,172.14,18%,1099.0
3,3,Bedside table with storage shelf,Modern Home,0.0,172.14,58%,1200.0
4,4,Wall Mounted TV Unit with Cabinet TV Stand Uni...,Modern Home,5.0,52.44,54%,1400.0
...,...,...,...,...,...,...,...
1995,1995,Casio Standard Analogue Ladys Standard Analog ...,Casio Standard Analogue Ladys Standard Analog ...,0.0,656.28,0%,1632.0
1996,1996,Coffee table + side table,Hub Furniture,0.0,172.14,0%,11450.0
1997,1997,Ben Togo Baby Bed,Bean GO,0.0,52.44,0%,550.0
1998,1998,Cloud memory foam mattress (medical),CIREM,0.0,172.14,9%,8495.0
1999,1999,Comfy memory foam mattress,CIREM,0.0,172.14,10%,10775.0

In [51]:
df.drop("Unnamed: 0",axis =1,inplace=True)
df

,furniture,type,rate,delivery,sale,price
0,Bed side table with storage shelf,Home Decor Center,3.3,172.14,72%,2500.0
1,Bed side table with storage shelf,Modern Home,0.0,172.14,54%,1200.0
2,Modern Zigzag TV Table,Modern Home,0.0,172.14,18%,1099.0
3,Bedside table with storage shelf,Modern Home,0.0,172.14,58%,1200.0
4,Wall Mounted TV Unit with Cabinet TV Stand Uni...,Modern Home,5.0,52.44,54%,1400.0
...,...,...,...,...,...,...
1995,Casio Standard Analogue Ladys Standard Analog ...,Casio Standard Analogue Ladys Standard Analog ...,0.0,656.28,0%,1632.0
1996,Coffee table + side table,Hub Furniture,0.0,172.14,0%,11450.0
1997,Ben Togo Baby Bed,Bean GO,0.0,52.44,0%,550.0
1998,Cloud memory foam mattress (medical),CIREM,0.0,172.14,9%,8495.0
1999,Comfy memory foam mattress,CIREM,0.0,172.14,10%,10775.0

In [52]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997     True
1998    False
1999    False
Length: 2000, dtype: bool

In [53]:
df.duplicated().sum()

np.int64(304)

In [54]:
df.drop_duplicates(inplace=True)

In [55]:
df["type"].unique()

<StringArray>
[                                                            'Home Decor Center',
                                                                   'Modern Home',
                                       'Modern Home Modern Tv Table   Black Oak',
                          'Modern Home Modern Table            cm   Light Brown',
                        'Sarcomisr Manager Medical Office Chair   Black   White',
                                                  'Rattan Folding Table   Biege',
 'Modern Home                                                                 W',
                                                                       'General',
                                                                     'Sarcomisr',
                                                           'tv covers Protector',
 ...
     'pcs Retro Sweet Eye Work Top Beverages Silicone Coasters skidproof  brown',
                                                                'Egypt Antiques',
                                      'camping hammock  person with tree straps',
                        'Crystal Door Knobs  Pcs    mm   Pcs    mm Clear Drawer',
                                           'Sedra Tala Waterproof Buff   Yellow',
                          'Bestway Pavillo Camping Stool Chair Seat Fold N   No',
                                    'Wall Mounted Folding Desk    x    cm Black',
                             'PVC Flocking Air Inflatable Travel Pillow Cushion',
                                'Sofa Chair Bean Bag Flocking PVC Garden Lounge',
            'Casio Standard Analogue Ladys Standard Analog Women s LTP V   G  A']
Length: 592, dtype: str

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['type'] = le.fit_transform(df['type'])

df

,furniture,type,rate,delivery,sale,price
0,Bed side table with storage shelf,173,3.3,172.14,72%,2500.0
1,Bed side table with storage shelf,272,0.0,172.14,54%,1200.0
2,Modern Zigzag TV Table,272,0.0,172.14,18%,1099.0
3,Bedside table with storage shelf,272,0.0,172.14,58%,1200.0
4,Wall Mounted TV Unit with Cabinet TV Stand Uni...,272,5.0,52.44,54%,1400.0
...,...,...,...,...,...,...
1992,Sofa Chair Bean Bag Flocking PVC Garden Lounge,484,0.0,566.00,44%,2498.0
1995,Casio Standard Analogue Ladys Standard Analog ...,53,0.0,656.28,0%,1632.0
1996,Coffee table + side table,213,0.0,172.14,0%,11450.0
1998,Cloud memory foam mattress (medical),45,0.0,172.14,9%,8495.0
1999,Comfy memory foam mattress,45,0.0,172.14,10%,10775.0

In [57]:
x = df.drop("price",axis=1)

In [58]:
y = df[["price"]]

In [59]:
x

,furniture,type,rate,delivery,sale
0,Bed side table with storage shelf,173,3.3,172.14,72%
1,Bed side table with storage shelf,272,0.0,172.14,54%
2,Modern Zigzag TV Table,272,0.0,172.14,18%
3,Bedside table with storage shelf,272,0.0,172.14,58%
4,Wall Mounted TV Unit with Cabinet TV Stand Uni...,272,5.0,52.44,54%
...,...,...,...,...,...
1992,Sofa Chair Bean Bag Flocking PVC Garden Lounge,484,0.0,566.00,44%
1995,Casio Standard Analogue Ladys Standard Analog ...,53,0.0,656.28,0%
1996,Coffee table + side table,213,0.0,172.14,0%
1998,Cloud memory foam mattress (medical),45,0.0,172.14,9%
1999,Comfy memory foam mattress,45,0.0,172.14,10%

In [60]:
y

        price
0      2500.0
1      1200.0
2      1099.0
3      1200.0
4      1400.0
...       ...
1992   2498.0
1995   1632.0
1996  11450.0
1998   8495.0
1999  10775.0

[1696 rows x 1 columns]

In [61]:
x_train , x_test , y_train , y_test = train_test_split(x , y ,random_state=42, test_size =0.2)
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((1356, 5), (1356, 1), (340, 5), (340, 1))

In [62]:
fur_pr = LinearRegression()
fur_pr.fit(x_train, y_train)

ValueError: could not convert string to float: 'Modern Home Office Desk - 90*40 - White/Black'